[[headers]]
  for = "/*"
  [headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  publish = "build"
  command = "npm run build"
[context.production.environment]
  NODE_ENV = "production"
  VITE_ERKENNINGEN_GRAPHQL_API_URL = "https://api.erkenningen.nl/graphql"
  VITE_ERKENNINGEN_ADMIN_URL = "https://administratie.erkenningen.nl"
  VITE_ERKENNINGEN_SITE_TYPE = "administratie"
  VITE_ERKENNINGEN_CONTENT_API_URL = "https://content.erkenningen.nl/api"
[context.acceptance.environment]
  NODE_ENV = "production"
  VITE_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
  VITE_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.erkenningen.nl"
  VITE_ERKENNINGEN_SITE_TYPE = "administratie"
  VITE_ERKENNINGEN_CONTENT_API_URL = "https://content.erkenningen.nl/api"
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.erkenningen.nl/graphql"
  VITE_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.erkenningen.nl"
  VITE_ERKENNINGEN_SITE_TYPE = "administratie"
  VITE_ERKENNINGEN_CONTENT_API_URL = "https://content.erkenningen.nl/api"
